version: '3.7'

services:
  sqlserver:
    container_name: sqlserver-db
    image: sqlserver:8.0
    environment:
      - SQLSERVER_DATABASE=live-score
      - SQLSERVER_USER=admin
      - SQLSERVER_PASSWORD=admin
      - SQLSERVER_ROOT_PASSWORD=adminroot
    ports:
      - "3306:3306"
    restart: always
    networks:
      - livescore
    volumes:
      - ./my-sql-data:/var/lib/sqlserver

  livescore:
    image: srinivasrepo/livescore:latest
    container_name: livescore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - livescore
    depends_on:
      - sqlserver
    environment:
      - SQLSERVER_HOST=sqlserver
      - SQLSERVER_USERNAME=admin
      - SQLSERVER_PASSWORD=admin
      - SQLSERVER_DATABASE=live-score
      - SQLSERVER_PORT=3306

networks:
  livescore:
    driver: bridge
