server:
  port: 8080

spring:
  application:
    name: LiveScore
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${SQLSERVER_HOST:localhost}:${SQLSERVER_PORT:3306}/${SQLSERVER_DATABASE:live_score}?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SQLSERVER_USERNAME:admin}
    password: ${SQLSERVER_PASSWORD:admin}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true

live-score:
  source-url: http://static.cricinfo.com/rss/livescores.xml
  jwt:
    secret: 5QVmYq3t6w9z$C&F)J@Mc%fTjWnZr4u7x!A%D*G-KaPdRgUkXp2s5v8y/B?E(H+Mb
    expiration: 86400
